services:
  postgres:
    image: postgres:16
    container_name: nba_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - nba_pgdata:/var/lib/postgresql/data

volumes:
  nba_pgdata:
